### ISSUE TITLE
SVG icons are not visible across all browsers.

### ISSUE THREAD

**Issue by sent0007** [sent0007/using-svg-icons#1]
Good evening, 
Markbot excepted my assignment but I was unable to see any of the SVG files through any browser. I've tried exporting for screens, optimizing the files and sprite sheet but nothing seems to be working. Hoping to figure out the problem here so I don't run into the problem down the road. Thanks!

![using-svg-icons-mozilla-firefox](https://user-images.githubusercontent.com/55108791/96042335-421d2e00-0e3b-11eb-9ce2-189dc0ba5540.png)

https://github.com/sent0007/using-svg-icons/blob/bf6155aa3e8be69f63279f9eba1aa2336441f428/index.html#L10-L35

https://github.com/sent0007/using-svg-icons/blob/bf6155aa3e8be69f63279f9eba1aa2336441f428/css/main.css#L19-L53

Appreciate the help!
@hellachella
@JessJodoin
@MacKenzieRose
@HannahDelaney

**Comment by JessJodoin** [comment]
When you opened the index, did you open it through Marbot by clicking the eyeball icon on the top left?

**Comment by JessJodoin** [comment]
Okay so I downloaded the zip for your repo and I figured out why you couldn't see them. When naming your artboards in illustrator you named them slightly different than how you targeted them in your `<svg> <use>`

These are what you named them brachiosaurusldpi, micropachycephalosaurusldpi, velociraptorldpi
So if you change the name after the # they should show up 

Hopefully that helps 😄

**Comment by sent0007** [comment]
Thanks for the quick reply! 

I renamed the artboards, exported for screens and optimized through spritebot, then placed them back in the images folder. I also made sure they were targeted correctly in the svg use tags. 

I'm still not seeing them in the browser. I feel like I'm missing something :confused:?

**Comment by JessJodoin** [comment]
When you open the index in a browser are you opening it through Markbot by clicking the eyeball icon (top left)? I threw your repo into markbot and opened it that way and I can see them

**Comment by sent0007** [comment]
Ah, thank you! They are showing now :blush:. I swear I tried that earlier in the assignment.
